# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aluhug/progexam/hallServer-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aluhug/progexam/hallServer-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aluhug/progexam/hallServer-master/CMakeFiles /home/aluhug/progexam/hallServer-master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aluhug/progexam/hallServer-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hallServer

# Build rule for target.
hallServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hallServer
.PHONY : hallServer

# fast build rule for target.
hallServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/build
.PHONY : hallServer/fast

#=============================================================================
# Target rules for targets named hallServer_autogen

# Build rule for target.
hallServer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hallServer_autogen
.PHONY : hallServer_autogen

# fast build rule for target.
hallServer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer_autogen.dir/build.make CMakeFiles/hallServer_autogen.dir/build
.PHONY : hallServer_autogen/fast

functions.o: functions.cpp.o
.PHONY : functions.o

# target to build an object file
functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/functions.cpp.o
.PHONY : functions.cpp.o

functions.i: functions.cpp.i
.PHONY : functions.i

# target to preprocess a source file
functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/functions.cpp.i
.PHONY : functions.cpp.i

functions.s: functions.cpp.s
.PHONY : functions.s

# target to generate assembly for a file
functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/functions.cpp.s
.PHONY : functions.cpp.s

hallServer_autogen/mocs_compilation.o: hallServer_autogen/mocs_compilation.cpp.o
.PHONY : hallServer_autogen/mocs_compilation.o

# target to build an object file
hallServer_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/hallServer_autogen/mocs_compilation.cpp.o
.PHONY : hallServer_autogen/mocs_compilation.cpp.o

hallServer_autogen/mocs_compilation.i: hallServer_autogen/mocs_compilation.cpp.i
.PHONY : hallServer_autogen/mocs_compilation.i

# target to preprocess a source file
hallServer_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/hallServer_autogen/mocs_compilation.cpp.i
.PHONY : hallServer_autogen/mocs_compilation.cpp.i

hallServer_autogen/mocs_compilation.s: hallServer_autogen/mocs_compilation.cpp.s
.PHONY : hallServer_autogen/mocs_compilation.s

# target to generate assembly for a file
hallServer_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/hallServer_autogen/mocs_compilation.cpp.s
.PHONY : hallServer_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/main.cpp.s
.PHONY : main.cpp.s

tcpserver.o: tcpserver.cpp.o
.PHONY : tcpserver.o

# target to build an object file
tcpserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/tcpserver.cpp.o
.PHONY : tcpserver.cpp.o

tcpserver.i: tcpserver.cpp.i
.PHONY : tcpserver.i

# target to preprocess a source file
tcpserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/tcpserver.cpp.i
.PHONY : tcpserver.cpp.i

tcpserver.s: tcpserver.cpp.s
.PHONY : tcpserver.s

# target to generate assembly for a file
tcpserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hallServer.dir/build.make CMakeFiles/hallServer.dir/tcpserver.cpp.s
.PHONY : tcpserver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hallServer_autogen"
	@echo "... hallServer"
	@echo "... functions.o"
	@echo "... functions.i"
	@echo "... functions.s"
	@echo "... hallServer_autogen/mocs_compilation.o"
	@echo "... hallServer_autogen/mocs_compilation.i"
	@echo "... hallServer_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tcpserver.o"
	@echo "... tcpserver.i"
	@echo "... tcpserver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

